export const USER_AUTH = "USER_AUTH";
export const USER_SIGNED_OUT = "USER_SIGNED_OUT";
export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_WEB_SETTINGS = "GET_WEB_SETTINGS";
export const TOGGLE_AUTH_MODAL = "TOGGLE_AUTH_MODAL";
export const TOGGLE_FOOTER = "TOGGLE_FOOTER";
